### ISSUE TITLE
[FEATURE REQUEST]: Improve tags for SEO

### ISSUE THREAD

**Issue by jescalada** [G-Research/ParquetSharp.DataFrame#14]
### Is your feature request related to a problem? Please describe.

Currently, we don't have any tags for ParquetSharp.DataFrame. I thought it would be good to add similar tags to ParquetSharp to help it rank better on GitHub searches as well as Google.

### Describe the solution you'd like

I would like to add keywords to increase the rank on both GitHub and Google, as well as making sure that the people that need to use the project, can find it.

The suggested tags are:
dataframe, csharp, dotnet, parquet, big-data

The keywords I'm optimizing for are:
- dataframe
  - High relevance (13k results)
- parquet dotnet
  - Medium relevance (19 results)
  - Not in results 
- dotnet dataframe
  - Low relevance (5 results)
  - Not in results
- csharp dataframe
  - Low relevance (5 results) 
  - Not in results

"big-data" was added for extra hits, since it has lots of results and may help raise rank when queried along with C#/.NET.

Feel free to make any suggestions or changes as required!

**Comment by jgiannuzzi** [comment]
I've added the tags as requested, thanks @jescalada!
